language: python
python:
  - "2.7"
services:
  - redis-server
before_install:
  - sudo apt-get update
  - sudo apt-get install -y -o Dpkg::Options::=--force-confnew python python-dev python-pip redis-server build-essential libevent-dev ircd-irc2
install:
  - pip install -r requirements.txt #--use-mirrors
before_script: 
  - mkdir -p ~/.willie/modules
  - ln -s $(pwd)/lumberjack.py ~/.willie/modules/
  - ln -s $(pwd)/doc/logbot.cfg ~/.willie/default.cfg
  - sed -i 's/^host =.*/host = 127.0.0.1/g' ~/.willie/default.cfg
  - sed -i 's/redis_host =.*/redis_host = 127.0.0.1/g' ~/.willie/default.cfg
  - sed -i "s/REDIS_HOST =.*/REDIS_HOST = '127.0.0.1'/g" config.py
script: willie -d && python web.py start && python web.py stop && willie -q
after_script: 
  - cat /tmp/web.log
