language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install python python-dev python-pip redis-server build-essential libevent-dev
install:
  - pip install -r requirements.txt #--use-mirrors
script: python web.py start; python web.py stop

