language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update
  - sudo apt-get install python python-dev python-pip redis-server build-essential libevent-dev
  - sudo apt-get install redis-server
install:
  - pip install -r requirements.txt #--use-mirrors
before_script: 
  - mkdir -p ~/.willie/modules
  - ls -ld ~/.willie/modules
  - ln -s lumberjack.py ~/.willie/modules/
  - ls -l ~/.willie/modules/lumberjack.py
  - ln -s doc/logbot.cfg ~/.willie/default.cfg
  - ls -l ~/.willie/default.cfg
  - sed -i 's/host =.*/host = 127.0.0.1/g' ~/.willie/default.cfg
  - sed -i "s/REDIS_HOST =.*/REDIS_HOST = '127.0.0.1'/g" config.py
script: willie -d; python web.py start; python web.py stop; willie -q; cat /tmp/web.log

